replicaCount: 1
image:
  repository: chait2199/go-web-app
  tag: "v1"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: {}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific